name: Deploy To Render Prod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Trigger Render Deploy
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl --request POST \
             --url https://api.render.com/v1/services/srv-cplpd9aj1k6c739odol0%2Fdeploys%2Fdep-cplpd9ij1k6c739odoog/deploys \
             --header 'accept: application/json' \
             --header 'content-type: application/json' \
             --header 'Authorization: Bearer $RENDER_API_KEY' \
             --data '{
               "clearCache": "do_not_clear"
             }'
